### ISSUE TITLE
Making my own native app registration multi-tenant

### ISSUE THREAD

**Issue by christophwille** [Azure-Samples/active-directory-dotnet-deviceprofile#4]
Quote from readme.md:

"The instructions so far leveraged the Azure AD entry for the app in our test tenant: given that the app is multitenant, anybody can run the sample against that app entry. "

How would I configure an application entry in *my* directory so that it is properly multi-tenant capable? Ie emulating the behavior of this app or azure cli. The Ibiza portal seems to be lacking a few settings for this.

**Comment by jmprieur** [comment]
Hello @christophwille, this article should provide you with the information you need: [How to sign in any Azure Active Directory (AD) user using the multi-tenant application pattern](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-devhowto-multi-tenant-overview)
