### ISSUE TITLE
The client has not listed any permissions for 'Microsoft Graph' in the requested permissions in the client's application registration

### ISSUE THREAD

**Issue by Tdawg90** [Azure-Samples/active-directory-dotnet-deviceprofile#8]
trying to run the sample out of the box, and I get this error when trying to authenticate 

_Sorry, but we’re having trouble signing you in.
AADSTS650056: Misconfigured application. This could be due to one of the following: The client has not listed any permissions for 'Microsoft Graph' in the requested permissions in the client's application registration. Or, The admin has not consented in the tenant. Or, Check the application identifier in the request to ensure it matches the configured client application identifier. Please contact your admin to fix the configuration or consent on behalf of the tenant. Client app ID: f5b5b9c9-c68b-45c5-8f57-bcf3f2f15f26._

This works with my C# WPF using Microsoft.Identity.Client;
```
string[] scopes = new string[] { "user.read" };
authResult = await app.AcquireTokenSilentAsync(**scopes**, accounts.FirstOrDefault());
```

but it doesn't look like Microsoft.IdentityModel.Clients.ActiveDirectory likes to take scopes
` result = await ctx.AcquireTokenSilentAsync(resource, clientId);`

**Comment by jmprieur** [comment]
1. If you are not tenant admin, you might want to configure the sample to work in your own tenant: 
https://github.com/Azure-Samples/active-directory-dotnet-deviceprofile/blob/master/README.md#optional-configure-the-sample-as-an-app-in-your-directory-tenant

2. ADAL.NET does not take scopes but resources (https://graph.microsoft.com). See https://aka.ms/adal-net-to-msal-net
